### ISSUE TITLE
Problem with self trained tensorflow model

### ISSUE THREAD

**Issue by vmi123** [Murthy10/tira#2]
Hi,

The model isn't working when I replaced your graph.pb and labels.txt file with mine in specified directory.
The error I am getting is 500(Server Error) but its working fine with your model.
Can you please help me out.

Also it would be very helpful for my use case if you can provide 5-10 images of some flowers which you have used to train your model.

**Comment by Murthy10** [comment]
Hi, 

I'm sorry for your issue this repository is not really active.

Could you post the stack trace of the server for further help?

**Comment by vmi123** [comment]
Can You please provide some(Around 10-15) images , 2-3 for some flowers where I can get accurate results if I try with your model.
As per my understanding i will get most accurate result when I will send any of images by which your model is trained.
It would be very helpful.

**Comment by Murthy10** [comment]
There is an image in the test folder (https://github.com/Murthy10/tira/tree/master/tira/tests/images)
I used the dataset from http://www.robots.ox.ac.uk/~vgg/data/flowers/102/index.html
(http://www.robots.ox.ac.uk/~vgg/data/flowers/102/102flowers.tgz)

**Comment by vmi123** [comment]
Here is the log:

E tensorflow/core/common_runtime/executor.cc:334] Executor failed to create kernel. Invalid argument: NodeDef mentions attr 'dct_method' not in Op<name=DecodeJpeg; signature=contents:string -> image:uint8; attr=channels:int,default=0; attr=ratio:int,default=1; attr=fancy_upscaling:bool,default=true; attr=try_recover_truncated:bool,default=false; attr=acceptable_fraction:float,default=1>; NodeDef: DecodeJpeg = DecodeJpeg[acceptable_fraction=1, channels=3, dct_method="", fancy_upscaling=true, ratio=1, try_recover_truncated=false, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_DecodeJpeg/contents_0)
         [[Node: DecodeJpeg = DecodeJpeg[acceptable_fraction=1, channels=3, dct_method="", fancy_upscaling=true, ratio=1, try_recover_truncated=false, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_DecodeJpeg/contents_0)]]
[pid: 34|app: 0|req: 1/1] 172.17.0.1 () {38 vars in 613 bytes} [Thu Mar 16 14:05:51 2017] POST /recognition/images => generated 27 bytes in 4334 msecs (HTTP/1.1 500) 2 headers in 92 bytes (1 switches on core 0)

**Comment by Murthy10** [comment]
Do you send a JPEG image to tira?

**Comment by vmi123** [comment]
The issue has been solved by upgrading to latest version of tensorflow.
Thanks for your help.
